baseURL = 'https://geminoa.strath.ai/'
languageCode = 'en-gb'
title = 'GEMINOA'
pluralizeListTitles = false

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 20

# [[menus.main]]
# name = 'Tags'
# pageRef = '/tags'
# weight = 30

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 30


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

